//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BlueKara_Design.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class CHUNG_VIDEOKARAOKE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CHUNG_VIDEOKARAOKE()
        {
            this.VIDEORECORDs = new HashSet<VIDEORECORD>();
            this.DETAILEACHSINGs = new HashSet<DETAILEACHSING>();
        }
    
        public string CategoryID { get; set; }
        public Nullable<int> Duaration { get; set; }
        public string FormatVideoID { get; set; }
        public string ID { get; set; }
        public string Name { get; set; }
    
        public virtual CATEGORY CATEGORY { get; set; }
        public virtual FORMATVIDEO FORMATVIDEO { get; set; }
        public virtual VIDEOOFFLINE VIDEOOFFLINE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VIDEORECORD> VIDEORECORDs { get; set; }
        public virtual VIDEOKARAOKE VIDEOKARAOKE { get; set; }
        public virtual VIDEOONLINE VIDEOONLINE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DETAILEACHSING> DETAILEACHSINGs { get; set; }
    }
}
