//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BlueKara_Design.Database
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DeepKaraEntities : DbContext
    {
        public DeepKaraEntities()
            : base("name=DeepKaraEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AVATAR> AVATARs { get; set; }
        public virtual DbSet<CATEGORY> CATEGORies { get; set; }
        public virtual DbSet<CHUNG_VIDEOKARAOKE> CHUNG_VIDEOKARAOKE { get; set; }
        public virtual DbSet<COMPOSER> COMPOSERs { get; set; }
        public virtual DbSet<DETAILEACHSING> DETAILEACHSINGs { get; set; }
        public virtual DbSet<FORMATVIDEO> FORMATVIDEOs { get; set; }
        public virtual DbSet<LEVEL> LEVELs { get; set; }
        public virtual DbSet<PARAMETER> PARAMETERs { get; set; }
        public virtual DbSet<PLAYER> PLAYERs { get; set; }
        public virtual DbSet<RECORDSTATU> RECORDSTATUS { get; set; }
        public virtual DbSet<SINGER> SINGERs { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<VIDEOKARAOKE> VIDEOKARAOKEs { get; set; }
        public virtual DbSet<VIDEOOFFLINE> VIDEOOFFLINEs { get; set; }
        public virtual DbSet<VIDEOONLINE> VIDEOONLINEs { get; set; }
        public virtual DbSet<VIDEORECORD> VIDEORECORDs { get; set; }
    }
}
